---
# - name: Enable and start systemd timers
#   ansible.builtin.systemd:
#     name: "{{ timer.name }}.timer"
#     enabled: "{{ timer.enabled | default(true) }}"
#     state: "{{ timer.state | default('started') }}"
#     daemon_reload: yes
#   loop: "{{ systemd_timers }}"
#   loop_control:
#     loop_var: timer
#   when: systemd_timers | length > 0
#   become: true

- import_tasks: units.yaml
  when: systemd_manage_units | default(false)

- import_tasks: timers.yaml
  when: systemd_manage_timers | default(false)

- import_tasks: services.yaml
  when: systemd_manage_services | default(true)
