---
- name: Ensure services are in a given state
  ansible.builtin.systemd:
    name: "{{ service.name }}"
    enabled: "{{ service.enabled | default(true) }}"
    state: "{{ service.state | default('started') }}"
  loop: "{{ systemd_service_name }}"
  loop_control:
    loop_var: service
  notify: reload systemd
  when: systemd_service_name is defined
  become: true

- name: Ensure timers are in a given state
  ansible.builtin.systemd:
    name: "{{ timer.name }}.timer"
    enabled: "{{ timer.enabled | default(true) }}"
    state: "{{ timer.state | default('started') }}"
  loop: "{{ systemd_timer_name }}"
  loop_control:
    loop_var: timer
  notify: reload systemd
  when: systemd_timer_name is defined
  become: true
