---
docker_apt_release_channel: "stable"
docker_apt_repository: "deb [arch=arm] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_daemon_options:
  storage-driver: "overlay2"
docker_prune_enabled: false
docker_obsolete_packages:
  - docker.io
  - docker
  - docker-engine
  - docker-compose
  - docker-doc
  - podman-docker
  - docker-compose-v2
  - containerd
  - runc