---
- name: Create a host directory for volume mapping
  ansible.builtin.file:
    path: "{{ dir.host_path }}"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ user_gid }}"
  loop: "{{ host_volume_dir }}"
  loop_control:
    loop_var: dir
  when: host_volume_dir | length > 0

- name: Create a file for the volume mapping with content
  ansible.builtin.copy:
    content: "{{ dir.content | default('') }}"
    dest: "{{ dir.host_path }}/{{ dir.file_name }}"
    owner: "{{ user_id }}"
    group: "{{ user_gid }}"
    mode: "{{ dir.file_mode | default('0644') }}"
  loop: "{{ host_volume_dir }}"
  loop_control:
    loop_var: dir
  when: host_volume_dir | length > 0 and dir.file_name is defined and dir.content is defined

- name: Create an empty file for the volume mapping
  ansible.builtin.file:
    path: "{{ dir.host_path }}/{{ dir.file_name }}"
    state: touch
    owner: "{{ user_id }}"
    group: "{{ user_gid }}"
  loop: "{{ host_volume_dir }}"
  loop_control:
    loop_var: dir
  when: host_volume_dir | length > 0 and dir.file_name is defined and dir.content is not defined

- name: Create a container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ item.name }}:{{ item.tag | default('latest') }}"
    cpus: "{{ cpu_limit | default(0.5) }}"
    memory: "{{ memory_limit | default('256M') }}"
    env: "{{ env_vars | default({}) }}"
    healthcheck:
      test: ["CMD-SHELL", "{{ healthcheck_cmd | default('exit 1') }}"]
      interval: "{{ healthcheck_interval | default('30s') }}"
      retries: "{{ healthcheck_retries | default(3) }}"
      start_period: "{{ healthcheck_start_period | default('10s') }}"
    published_ports: "{{ ports | default([]) }}"
    user: "{{ user_id }}:{{ user_gid }}"
    volumes: "{{ c_volumes | default([]) }}"
    state: started
    loop: "{{ docker_image_info }}"
    loop_control:
      loop_var: item
