---
- name: Create a host directory for volume mapping
  ansible.builtin.file:
    path: "{{ dir.host_path }}"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ user_gid }}"
  loop: "{{ host_volume_dir }}"
  loop_control:
    loop_var: dir
  when: host_volume_dir | length > 0

- name: Create a file for the volume mapping with content
  ansible.builtin.copy:
    content: "{{ dir.content | default('') }}"
    dest: "{{ dir.host_path }}/{{ dir.file_name }}"
    owner: "{{ user_id }}"
    group: "{{ user_gid }}"
    mode: "{{ dir.file_mode | default('0644') }}"
  loop: "{{ host_volume_dir }}"
  loop_control:
    loop_var: dir
  when: host_volume_dir | length > 0 and dir.file_name is defined and dir.content is defined

- name: Create an empty file for the volume mapping
  ansible.builtin.file:
    path: "{{ dir.host_path }}/{{ dir.file_name }}"
    state: touch
    owner: "{{ user_id }}"
    group: "{{ user_gid }}"
  loop: "{{ host_volume_dir }}"
  loop_control:
    loop_var: dir
  when: host_volume_dir | length > 0 and dir.file_name is defined and dir.content is not defined

- name: Create a container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_info.name }}:{{ docker_image_info.tag | default('latest') }}"
    cpus: "{{ cpu_limit | default(0.5) }}"
    memory: "{{ memory_limit }}"
    env: "{{ env_vars | default({}) }}"
    entrypoint: "{{ entrypoint | default(omit) }}"
    command: "{{ command | default(omit) }}"
    healthcheck:
      test: ["CMD-SHELL", "{{ healthcheck_cmd | default(omit) }}"]
      interval: "{{ healthcheck_interval | default('10s') }}"
      retries: "{{ healthcheck_retries | default(5) | int }}"
      start_period: "{{ healthcheck_start_period | default('15s') }}"
    published_ports: "{{ ports | default(omit) }}"
    user: "{{ user_id }}:{{ user_gid }}"
    volumes: "{{ volumes | default([]) }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    container_default_behavior: "{{ container_default_behavior }}"
    privileged: "{{ privileged | default(false) }}"
    devices: "{{ devices | default(omit) }}"
  when: docker_image_info | length > 0
    # loop: "{{ docker_image_info }}"
    # loop_control:
    #   loop_var: item

- name: Assert container passes healthcheck
  community.docker.docker_container_info:
    name: "{{ container_name }}"
  register: container_healthcheck
  until: "container_healthcheck.container.State.Health.Status == 'healthy'"
  retries: 5
  delay: 10
  when: healthcheck_cmd is defined and healthcheck_cmd != ""

- name: Wait for service to become responsive
  ansible.builtin.wait_for:
    host: "localhost"
    port: "{{ ports[0].split(':')[0] }}"
    state: started
    delay: 5
    timeout: 30
  when: ports is defined and ports | length > 0