---
- name: Continue if docker is installed, else exit
  ansible.builtin.command: docker --version
  register: docker_check
  ignore_errors: yes
  changed_when: false

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed on this host. Please install Docker to proceed."
  when: docker_check.rc != 0

- ansible.builtin.import_tasks: pull.yaml
  when: docker_image_info is defined

- ansible.builtin.import_tasks: network.yaml
  when: create_docker_network is defined

- ansible.builtin.import_tasks: container.yaml
  when: docker_image_info is defined