---
# check if image is present
# if not pull the image with specific tag
# set name and envs for the image
# specify ports and volumes if needed
# 
# - name: Check if image is present
#   community.docker.docker_image_info:
#     name: "{{ image.name }}:{{ image.tag }}"
#   register: image_info
#   loop: "{{ docker_image_info }}"
#   loop_control:
#     loop_var: image
  
# - name: Debug image info
#   ansible.builtin.debug:
#     var: image_info

- name: pull an image
  community.docker.docker_image_pull:
    name: "{{ docker_image_info.name }}"
    tag: "{{ docker_image_info.tag | default('latest') }}"
    platform: linux/arm/v7
    pull: not_present
    docker_host: "{{ docker_host }}"
  when: docker_image_info | length > 0
  # when: image_info.images | length == 0
  # loop: "{{ docker_image_info }}"
  # loop_control:
  #   loop_var: image