docker_image_info: []
image_names: ""
docker_host: unix:///var/run/docker.sock
# image_tag: ""
container_name: ""
cpu_limit: ""
memory_limit: ""
env_vars: {}
healthcheck_cmd: ""
healthcheck_interval: ""
healthcheck_retries: ""
healthcheck_start_period: ""
ports: []
volumes: []
host_volume_dir: []
file_name: ""