---
- name: Ensure apt is using HTTPS
  ansible.builtin.apt:
    name: "{{ item  }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name: "{{ docker_obsolete_packages }}"
    state: absent

- name: Ensure keyrings directory is not present
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent
  become: true

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  become: true

- name: Install Docker cli CE and runtime
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    autoremove: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true
  when: docker_install_enabled

- name: Configure Docker daemon options
  ansible.builtin.template:
    src: "templates/docker_daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: 'mubashir'
    group: 'mubashir'
    mode: '0644'
  notify: Restart Docker
  become: true
  when: update_docker_daemon_config

- name: Ensure docker service is enabled & running
  ansible.builtin.systemd:
    name: "{{ services }}"
    enabled: true
    state: started
  become: true
  loop:
    - docker.service
    - containerd.service
  loop_control:
    loop_var: services

- name: Add mubashir to docker group
  ansible.builtin.user:
    name: mubashir
    groups: docker
    append: true
  become: true

- name: Add Systemd service for docker prune
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_services:
      - description: "Docker prune"
        name: "docker_prune"
        exec_start: "docker system prune -f"
        type: "oneshot"
    systemd_manage_units: true
  when: docker_prune_enabled
  # become: true

- name: Add systemd timer for docker prune
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_timers:
      - description: "Docker prune"
        name: "docker_prune"
        on_calendar: "weekly"
    systemd_manage_timers: true
  when: docker_prune_enabled
  # become: true

- name: Ensure docker prune timer is enabled and started
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_manage_services: true
    systemd_timer_name:
      - name: docker_prune
        enabled: true
  when: docker_prune_enabled
  # become: true

- name: Restart docker service
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_manage_services: true
    systemd_service_name:
      - name: docker.service
        state: restarted
  when: restart_docker_service