- name: Install Pi-hole dependencies
  apt:
    name:
      - curl
      - dnsutils
    state: present
  become: true

- name: Check if Pi-hole is already installed
  ansible.builtin.stat:
    path: /etc/pihole/pihole-FTL.conf
  register: pihole_installed

- name: Install Pi-hole (unattended)
  ansible.builtin.shell: |
    curl -sSL https://install.pi-hole.net | \
    PIHOLE_INTERFACE={{ pihole_interface }} \
    TZ={{ timezone }} \
    QUERY_LOGGING: {{ query_logging }}
    DNSMASQ_LISTENING=single \
    PIHOLE_DNS_1={{ pihole_dns_1 }} \
    PIHOLE_DNS_2={{ pihole_dns_2 }} \
    WEBPASSWORD={{ pihole_web_password }} \
    bash /dev/stdin --unattended
  when: not pihole_installed.stat.exists
  become: true

- name: Ensure Pi-hole service is enabled and started
  ansible.builtin.include_tasks: "{{ dirs.systemd.tasks }}/main.yaml"
  vars:
    systemd_services:
      - name: pihole-FTL
        enabled: true
        state: started

- name: Add "mubashir" user to pihole group
  ansible.builtin.user:
    name: mubashir
    groups: pihole
    append: yes
  become: true