- name: Install Pi-hole dependencies
  apt:
    name:
      - curl
      - dnsutils
      - sqlite3
    state: present
  become: true

- name: Check if Pi-hole is already installed
  ansible.builtin.stat:
    path: /etc/pihole/pihole.toml
  register: pihole_installed
  become: true

- name: Check status of Pi-hole 
  ansible.builtin.debug:
    msg: " Pihole installed status {{ pihole_installed.stat.exists }}"

- name: Create Pi-hole configuration directory
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    mode: '0755'
  become: true
  when: not pihole_installed.stat.exists

- name: Pre-configure Pi-hole setupVars
  ansible.builtin.copy:
    dest: /etc/pihole/setupVars.conf
    content: |
      PIHOLE_INTERFACE={{ pihole_interface }}
      TZ={{ timezone }}
      DNSMASQ_LISTENING=single
      PIHOLE_DNS_1={{ pihole_dns_1 }}
      PIHOLE_DNS_2={{ pihole_dns_2 }}
      QUERY_LOGGING={{ query_logging }}
      INSTALL_WEB_INTERFACE=true
      WEBPASSWORD={{ pihole_web_password }}
  become: true
  when: not pihole_installed.stat.exists

- name: Install Pi-hole (unattended)
  ansible.builtin.shell: |
    set -eux
    set -o pipefail
    curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended
  args:
    executable: /bin/bash
    creates: /usr/local/bin/pihole
  when: not pihole_installed.stat.exists
  become: true

- name: Ensure Pi-hole service is enabled and started
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_manage_units: false
    systemd_manage_timers: false
    systemd_manage_services: true
    systemd_services:
      - name: pihole-FTL.service
        enabled: true
        state: started
  when: pihole_installed.stat.exists

- name: Add "mubashir" user to pihole group
  ansible.builtin.user:
    name: mubashir
    groups: pihole
    append: yes
  become: true
  when: not pihole_installed.stat.exists

- name: Backup Pi-hole settings weekly using systemd timer and service
  ansible.builtin.include_role:
    name: systemd
  vars:
    systemd_manage_timers: true
    systemd_timers:
      - name: pihole-backup
        description: "Query database backup"
        on_calendar: "weekly"
        unit: pihole-backup.service
    systemd_timer_name:
      - name: pihole-backup
        enabled: true
        state: started
    systemd_manage_units: true
    systemd_services: #Creates systemd unit file
      - name: pihole-backup
        wants: pihole-backup.timer
        after: network.target
        exec_start: sqlite3 /etc/pihole/pihole-FTL.db ".backup /home/mubashir/pihole-querydb-backup/pihole-FTL_$(date +"%d-%m-%Y_%H-%M-%S").db"
    systemd_service_name:
      - name: pihole-backup
        enabled: true
        state: started
  when: pihole_enable_backup #when is evaluated at runtime
