---
- name: Deploy Node Exporter
  hosts: monitoring #infra
  become: true
  roles:
  - role: node-exporter
    vars:
      node_exporter_install: true
      node_exporter_version: "1.8.0"
      system_architecture: "armv7" #for pi1=armv6
      create_systemd_service: true