- name: Deploy Task Tracker
  hosts: monitoring
  become: true
  roles:
    - role: deploy-docker
      vars:
        docker_image_info:
          name: mubashirusman/task-tracker
          tag: slim-trixie-1.0.1-arm-v7
        container_name: task-tracker
        ports:
          - "7000:8000"
        user_id: 6000
        user_gid: 6000
        host_volume_dir:
          - host_path: /opt/task-tracker/data
        volumes:
          - /opt/task-tracker/data:/app/data
        cpu_limit: 1
        memory_limit: 256M
    - role: deploy-docker
      vars:
        create_docker_network:
          name: applications
        docker_network_connect:
            container_name: task-tracker

